"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from decouple import Config, RepositoryEnv
from datetime import timedelta
from urllib.parse import urlparse, unquote
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Single source of truth: root-level .env (one directory above Backend/)
ROOT_DIR = BASE_DIR.parent
config = Config(RepositoryEnv(str(ROOT_DIR / '.env')))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')  # No default — server will refuse to start without a real key

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=True, cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', cast=lambda v: [s.strip() for s in v.split(',')])


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third-party apps
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',

    # Local apps
    'apps.users',
    'apps.events',
    # 'apps.bets',
    'apps.umamusume',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # CORS middleware (must be before CommonMiddleware)
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

def _database_config_from_url(database_url: str) -> dict:
    """
    Parse DATABASE_URL into Django DATABASES['default'] dict.
    Expected MySQL format:
      mysql://USER:PASSWORD@HOST:PORT/DB_NAME
    Or SQLite format:
      sqlite:///path/to/db.sqlite3
    """
    parsed = urlparse(database_url)

    if parsed.scheme == 'sqlite':
        return {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }

    if parsed.scheme not in ('mysql', 'mysql2'):
        raise ValueError("DATABASE_URL must start with mysql:// or sqlite://")

    if not parsed.path or parsed.path == '/':
        raise ValueError("DATABASE_URL is missing the database name (path)")

    return {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': parsed.path.lstrip('/'),
        'USER': unquote(parsed.username or ''),
        'PASSWORD': unquote(parsed.password or ''),
        'HOST': parsed.hostname or '',
        'PORT': int(parsed.port or 3306),
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
        },
    }

DATABASES = {
    'default': _database_config_from_url(config('DATABASE_URL')),
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media files (User uploads like profile pictures)
# https://docs.djangoproject.com/en/5.2/topics/files/
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Production security settings (only active when DEBUG=False)
if not DEBUG:
    # Trust the X-Forwarded-Proto header set by Cloudflare/reverse proxy
    # so Django knows the original request was HTTPS even though Nginx
    # only receives plain HTTP from the Cloudflare Tunnel internally.
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    # Do NOT redirect in Django — Cloudflare/Nginx handles HTTP→HTTPS
    SECURE_SSL_REDIRECT = False

    # Tell browsers to use HTTPS exclusively for 1 year
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

    # Cookies are only sent over HTTPS
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

    # Prevent MIME-type sniffing
    SECURE_CONTENT_TYPE_NOSNIFF = True

    # XSS protection header for legacy browsers
    SECURE_BROWSER_XSS_FILTER = True

    # Clickjacking protection
    X_FRAME_OPTIONS = 'DENY'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom User Model
AUTH_USER_MODEL = 'users.User'

# REST Framework Settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
    # Throttling disabled for testing
    # 'DEFAULT_THROTTLE_CLASSES': [
    #     'rest_framework.throttling.AnonRateThrottle',
    #     'rest_framework.throttling.UserRateThrottle'
    # ],
    # 'DEFAULT_THROTTLE_RATES': {
    #     'anon': '10/day',
    #     'user': '100/day'
    # },
    # DEBUG=True  → full exception class, message, and stack trace
    # DEBUG=False → generic "unexpected error" message only
    'EXCEPTION_HANDLER': 'config.exception_handler.custom_exception_handler',
}

# JWT Settings
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
}

# CORS Settings
CORS_ALLOWED_ORIGINS = config(
    'CORS_ALLOWED_ORIGINS',
    default='http://localhost:5173,http://127.0.0.1:5173,http://localhost:8080,http://127.0.0.1:8080,http://localhost:8081,http://127.0.0.1:8081',
    cast=lambda v: [s.strip() for s in v.split(',')]
)

CORS_ALLOW_CREDENTIALS = True

CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# ---------------------------------------------------------------------------
# Logging
# LOG_DIR defaults to Backend/logs/ for development.
# In production set LOG_DIR=/var/log/derby-bets in .env
# ---------------------------------------------------------------------------
LOG_DIR = config('LOG_DIR', default=str(BASE_DIR / 'logs'))
os.makedirs(LOG_DIR, exist_ok=True)

# Remote syslog server — DB values take priority over .env so the admin
# panel can override them. Falls back to .env on first boot before DB is ready.
SYSLOG_HOST = config('SYSLOG_HOST', default='')
SYSLOG_PORT = config('SYSLOG_PORT', default=514, cast=int)

try:
    from apps.users.models import SystemSettings as _SS
    _db_host = _SS.get_setting('SYSLOG_HOST', None)
    _db_port = _SS.get_setting('SYSLOG_PORT', None)
    if _db_host is not None:
        SYSLOG_HOST = _db_host
    if _db_port is not None:
        SYSLOG_PORT = int(_db_port)
except Exception:
    pass  # DB not ready yet (migrations, first run) — use .env values

# Build handler list and handler dict dynamically.
# syslog_remote is only defined when SYSLOG_HOST is non-empty — defining it
# with an empty host causes SysLogHandler to call socket.getaddrinfo('', 514)
# at Django startup which raises ValueError and crashes migrations/gunicorn.
_security_handlers = ['security_file', 'console']
_extra_handlers = {}
if SYSLOG_HOST:
    _security_handlers.append('syslog_remote')
    _extra_handlers['syslog_remote'] = {
        'class': 'logging.handlers.SysLogHandler',
        'address': (SYSLOG_HOST, SYSLOG_PORT),
        'facility': 'local0',
        'formatter': 'syslog',
    }

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'security': {
            'format': '{asctime} | {levelname} | {name} | {message}',
            'style': '{',
            'datefmt': '%Y-%m-%dT%H:%M:%S%z',
        },
        'verbose': {
            'format': '{asctime} | {levelname} | {name} | {module} | {message}',
            'style': '{',
            'datefmt': '%Y-%m-%dT%H:%M:%S%z',
        },
        # Syslog format: plain message — rsyslog adds its own timestamp/host
        'syslog': {
            'format': 'derby-bets: {levelname} | {message}',
            'style': '{',
        },
    },
    'handlers': {
        'security_file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(LOG_DIR, 'security.log'),
            'maxBytes': 10 * 1024 * 1024,  # 10 MB per file
            'backupCount': 30,
            'formatter': 'security',
            'encoding': 'utf-8',
        },
        'app_file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(LOG_DIR, 'app.log'),
            'maxBytes': 10 * 1024 * 1024,
            'backupCount': 10,
            'formatter': 'verbose',
            'encoding': 'utf-8',
        },
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        **_extra_handlers,
    },
    'loggers': {
        # Security events: login failures, lockouts, unlocks, logouts
        'security': {
            'handlers': _security_handlers,
            'level': 'INFO',
            'propagate': False,
        },
        # General Django warnings/errors
        'django': {
            'handlers': ['app_file', 'console'],
            'level': 'WARNING',
            'propagate': False,
        },
        # Unhandled request errors (caught by exception_handler.py)
        'django.request': {
            'handlers': ['app_file'],
            'level': 'ERROR',
            'propagate': False,
        },
    },
}
