# Generated by Django 5.2.8 on 2025-11-30 05:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=5000.0, max_digits=10)),
                ('total_bets_placed', models.IntegerField(default=0)),
                ('total_bets_won', models.IntegerField(default=0)),
                ('total_bets_lost', models.IntegerField(default=0)),
                ('total_winnings', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_losses', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('bio', models.TextField(blank=True, max_length=500, null=True)),
                ('avatar_url', models.URLField(blank=True, null=True)),
                ('favorite_umamusume', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'db_table': 'user_profiles',
            },
        ),
    ]
