# Generated by Django 5.2.8 on 2025-12-26 05:16

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('umamusume', '0002_umas_skill_is_unique_skill_uma_umamusume_uma'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.URLField(blank=True, null=True)),
                ('distance', models.CharField(max_length=10)),
                ('dist_category', models.CharField(choices=[('Sprint', 'Sprint'), ('Mile', 'Mile'), ('Medium', 'Medium'), ('Long', 'Long')], default='Sprint', max_length=10)),
                ('direction', models.CharField(choices=[('left', 'left'), ('right', 'right'), ('straight', 'straight')], default='right', max_length=10)),
                ('track_type', models.CharField(choices=[('turf', 'turf'), ('dirt', 'dirt')], default='turf', max_length=10)),
            ],
            options={
                'db_table': 'tracks',
            },
        ),
        migrations.CreateModel(
            name='RaceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('scheduled', 'scheduled'), ('open', 'open'), ('active', 'active'), ('race_ongoing', 'race_ongoing'), ('completed', 'completed')], default='scheduled', max_length=50)),
                ('opening_dt', models.DateTimeField(null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('active_dt', models.DateTimeField(null=True)),
                ('race_start_dt', models.DateTimeField(null=True)),
                ('race_end_dt', models.DateTimeField(null=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='races', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'race_event',
            },
        ),
        migrations.CreateModel(
            name='Bids',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=5000.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bidder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to=settings.AUTH_USER_MODEL)),
                ('race_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='events.raceevent')),
            ],
            options={
                'db_table': 'race_bids',
            },
        ),
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.IntegerField(default=1, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('race_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='events.raceevent')),
                ('umamusume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='umamusume.umamusume')),
            ],
            options={
                'db_table': 'race_results',
            },
        ),
    ]
