# Generated by Django 5.2.8 on 2026-02-03 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_raceevent_track'),
    ]

    operations = [
        migrations.AddField(
            model_name='bids',
            name='uma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='events.results'),
        ),
    ]
