# Generated by Django 5.2.8 on 2026-04-10 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_track_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='raceevent',
            name='is_published',
        ),
    ]
