# Generated by Django 5.2.8 on 2026-02-03 08:12

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('is_unique', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'skills',
            },
        ),
        migrations.CreateModel(
            name='Umas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('avatar_url', models.URLField(blank=True)),
            ],
            options={
                'db_table': 'umas',
            },
        ),
        migrations.CreateModel(
            name='Umamusume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('avatar_url', models.URLField(blank=True, null=True)),
                ('speed', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(1200)])),
                ('stamina', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(1200)])),
                ('power', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(1200)])),
                ('guts', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(1200)])),
                ('wit', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(1200)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('skills', models.ManyToManyField(db_table='uma_skills', related_name='learned_by', to='umamusume.skill')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='umamusumes', to=settings.AUTH_USER_MODEL)),
                ('uma', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='umamusume', to='umamusume.umas')),
            ],
            options={
                'db_table': 'umamusume',
            },
        ),
        migrations.CreateModel(
            name='Aptitude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turf', models.CharField(choices=[('S', 'S'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G')], default='G', max_length=1)),
                ('dirt', models.CharField(choices=[('S', 'S'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G')], default='G', max_length=1)),
                ('short', models.CharField(choices=[('S', 'S'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G')], default='G', max_length=1)),
                ('mile', models.CharField(choices=[('S', 'S'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G')], default='G', max_length=1)),
                ('medium', models.CharField(choices=[('S', 'S'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G')], default='G', max_length=1)),
                ('long', models.CharField(choices=[('S', 'S'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G')], default='G', max_length=1)),
                ('front', models.CharField(choices=[('S', 'S'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G')], default='G', max_length=1)),
                ('pace', models.CharField(choices=[('S', 'S'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G')], default='G', max_length=1)),
                ('late', models.CharField(choices=[('S', 'S'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G')], default='G', max_length=1)),
                ('end', models.CharField(choices=[('S', 'S'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G')], default='G', max_length=1)),
                ('umamusume', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='aptitudes', to='umamusume.umamusume')),
            ],
            options={
                'db_table': 'aptitudes',
            },
        ),
        migrations.AddField(
            model_name='skill',
            name='uma',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unique_skill', to='umamusume.umas'),
        ),
    ]
