# Generated by Django 5.2.8 on 2026-04-09 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umamusume', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='umas',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
