# Generated by Django 5.2.8 on 2025-12-18 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umamusume', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Umas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('avatar_url', models.URLField(blank=True)),
            ],
            options={
                'db_table': 'umas',
            },
        ),
        migrations.AddField(
            model_name='skill',
            name='is_unique',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='uma',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unique_skill', to='umamusume.umas'),
        ),
        migrations.AddField(
            model_name='umamusume',
            name='uma',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='umamusume', to='umamusume.umas'),
        ),
    ]
