# Generated by Django 5.2.8 on 2026-04-09 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umamusume', '0002_umas_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='umamusume',
            name='avatar_url',
        ),
        migrations.RemoveField(
            model_name='umas',
            name='avatar_url',
        ),
        migrations.AddField(
            model_name='umamusume',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='umamusume_avatars/'),
        ),
        migrations.AddField(
            model_name='umas',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='uma_avatars/'),
        ),
    ]
